### ISSUE TITLE
bfs_test.cpp fails

### ISSUE THREAD

**Issue by Vytautas-Hermann** [thm-mni-ii/sea#110]
/home/vytautas/Dokumente/sea/test/bfs_test.cpp:39: Failure
Expected equality of these values:
  c2
    wich is: 0
  order * degree
    wich is: 10000

I'm getting this message while running the tests.

**Comment by shsr04** [comment]
Sorry for the late reply, I didn't get a notification.
And, it also works on my machine... No idea what causes this problem.

**Comment by shsr04** [comment]
Possibly fixed by #111
