### ISSUE TITLE
Improve the doc comments.

### ISSUE THREAD

**Issue by andrej-sajenko** [thm-mni-ii/sea#16]
https://github.com/thm-mni-ii/sea/blob/c13e0b877a9799f85ef3fd11e134ee41ff402860/include/sealib/graphcreator.h#L23

@1yay1 For what does the 2 stands?

**Comment by jmeintrup** [comment]
The number denotes the amount of edges. 
I.e. it's for multiple edges with the same endpoints so the structure can support multigraphs.
