### ISSUE TITLE
Linear Time DFS

### ISSUE THREAD

**Issue by andrej-sajenko** [thm-mni-ii/sea#4]
Implement a linear time DFS on 

* directed
* undirected

graphs using O(log n) extra bits

**Comment by shsr04** [comment]
Hello, I have created a first approach to DFS. It runs in O(n+m) time, and the implicit runtime stack used by the recursion in `process(u)` requires O(n log n) bits.

- [X]  simple DFS with implicit recursion stack: O(n+m) time, O(n log n) bits
  #11 
- [x] explicit, segmented runtime stack: for O((n+m) log n) time and O((ld3 + &#949;) n) bits
  #13 
- [x] segment storage and intermediate restoration: for O(n+m) time and O(n log log n) bits
  #41
- [x] static space allocation of outgoing edges: O(n+m) time and O(n+m) bits
  #65 

### [-> Forked sealib repo](https://github.com/shsr04/sea)
