### ISSUE TITLE
Master is not up to date

### ISSUE THREAD

**Issue by shsr04** [thm-mni-ii/sea#49]
Some files got reset to an earlier state with the latest merge, for example
```
src/bfs.cpp
src/dfs.h
src/segmentstack.cpp
...
```

Some important fixes that were already in `master` have been reverted. This happened because the source branch that was merged into master was out-of-date.

Please `reset` to the previous state and make a clean merge, or everyone will have local conflicts.

**Comment by andrej-sajenko** [comment]
I have reverted the changes. The build was also broken on OSX.
We will include the changes next week again (after we have fixed the issues.)
